title: ธรรมสุตตะ
description: รวมพระไตรปิฎก วินัยปิฎก สุตตันตปิฎก อภิธรรมปิฎก และสาระธรรมต่าง ๆ
baseurl: "" # อย่าใส่ /tripidok หรือ path ใด ๆ
url: "https://dhamma-sutta.com"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# การตั้งค่าระดับ global สำหรับโพสต์
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# เมนูหลักด้านบน (เพิ่มได้ตามต้องการ)
navigation:
  - title: "หน้าแรก"
    url: "/"
  - title: "โพสต์"
    url: /posts/
  - title: "หมวดหมู่"
    url: /categories/
  - title: "แท็ก"
    url: /tags/

# Social (จะขึ้นที่ด้านล่างหรือ author_profile)
author:
  name   : ธรรมสุตตะ
  avatar : "/assets/images/avatar.png"
  bio    : "รวมคำสอนพระพุทธเจ้าในรูปแบบเว็บไซต์อ่านง่าย"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dhamsutta"
    - label: "เว็บไซต์หลัก"
      icon: "fas fa-fw fa-link"
      url: "https://dhamma-sutta.com"

related: true