title: ""
logo: "/assets/images/logo25.gif"
description: รวมพระไตรปิฎก วินัยปิฎก สุตตันตปิฎก อภิธรรมปิฎก และสาระธรรมต่าง ๆ
baseurl: "" # อย่าใส่ /tripidok หรือ path ใด ๆ
url: "https://dhamma-sutta.com"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

header_pages:
  - index.md

# การตั้งค่าระดับ global สำหรับโพสต์
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false

# เมนูหลักด้านบน (เพิ่มได้ตามต้องการ)
navigation:
  - title: "หน้าแรก"
    url: /

  - title: "หมวดหมู่"
    children:
      - title: "พระวินัย"
        url: /categories/พระวินัย/
      - title: "พระสูตร"
        url: /categories/พระสูตร/
      - title: "พระอภิธรรม"
        url: /categories/พระอภิธรรม/
      - title: "ทั้งหมด"
        url: /categories/

  - title: "ธรรมบรรยาย"
    url: /radio/

  - title: "อภิธานศัพท์"
    url: /dic/

