title: ""
logo: "/assets/images/logo25.gif"
description: รวมพระไตรปิฎก วินัยปิฎก สุตตันตปิฎก อภิธรรมปิฎก และสาระธรรมต่าง ๆ
baseurl: "" # อย่าใส่ /tripidok หรือ path ใด ๆ
url: "https://dhamma-sutta.com"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# การตั้งค่าระดับ global สำหรับโพสต์
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false

# เมนูหลักด้านบน (เพิ่มได้ตามต้องการ)
navigation:
  - title: "หน้าแรก"
    url: /

  - title: "หมวดหมู่"
    children:
      - title: "พระวินัย"
        url: /categories/พระวินัย/
      - title: "พระสูตร"
        url: /categories/พระสูตร/
      - title: "พระอภิธรรม"
        url: /categories/พระอภิธรรม/
      - title: "ทั้งหมด"
        url: /categories/

  - title: "ธรรมบรรยาย"
    url: /radio/

  - title: "อภิธานศัพท์"
    url: /dic/

# Social (จะขึ้นที่ด้านล่างหรือ author_profile)
author:
  name   : ธรรมสุตตะ
  avatar : "/assets/images/logo_no_bg.png"
  bio    : "ศึกษาพระธรรมตามพระไตรปิฏก"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dhamsutta"
    - label: "เว็บไซต์หลัก"
      icon: "fas fa-fw fa-link"
      url: "https://dhamma-sutta.com"

related: true

# เปิดใช้ sidebar
minimal_mistakes_skin: default
sidebar:
  nav: "main"
