title: "ธรรมสุตตะ"
logo: "/assets/images/logo25.gif"
description: รวมพระไตรปิฎก วินัยปิฎก สุตตันตปิฎก อภิธรรมปิฎก และสาระธรรมต่าง ๆ
baseurl: ""
url: "https://dhamma-sutta.com"

remote_theme: "mmistakes/minimal-mistakes"

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

navigation:
  - title: "หน้าแรก"
    url: /

  - title: "หมวดหมู่"
    children:
      - title: "พระวินัย"
        url: /vinaya/
      - title: "พระสูตร"
        url: /sutta/
      - title: "พระอภิธรรม"
        url: /abidhamma/
      - title: "ทั้งหมด"
        url: /categories/

  - title: "ธรรมบรรยาย"
    url: /radio/

  - title: "อภิธานศัพท์"
    url: /dic/

author:
  name   : ธรรมสุตตะ
  avatar : "/assets/images/logo_no_bg.png"
  bio    : "ศึกษาพระธรรมตามพระไตรปิฏก"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dhamsutta"
    - label: "เว็บไซต์หลัก"
      icon: "fas fa-fw fa-link"
      url: "https://dhamma-sutta.com"

minimal_mistakes_skin: default
permalink: /:categories/:title/

sass:
  style: compressed

include:
  - assets/css/custom.css

footer:
  links: [] # ล้างลิงก์ทั้งหมด